### ISSUE TITLE
Certain Special Keys may not be working

### ISSUE THREAD

**Issue by BrianBATL** [bitfocus/companion-module-vicreo-hotkey#46] opened 2022-03-20 21:52 UTC
You closed my previous bug report, so unfortunately I have to submit a new one even though the issue is still related.

Previously, virtually no Vicreo hotkeys were working, and that was clearly because I was not using the Companion 2.2.0 beta version with the 3.0.3 Listener version.  So I did what you said and updated.  I am currently using the latest versions of everything.  Companion 2.2.0+3998-ccea40c7, which allowed me to set >3.0.0 in the config, and Vicreo 3.0.3.  And I'm running on Windows10.

As mentioned, this fixed the vast majority of my buttons that use Vicreo Hotkey, however there are still several that do not work.  And as far as I can tell, it appears limited to just certain Special Keys.

For example, the single hotkey Special Key "Space" does NOT execute a spacebar press.  "Delete" does not execute either.

I debugged this by loading up Notepad and filled some lines up with letters, then tried those buttons and they did nothing.  No spaces created between letters and no letters deleted.  Pretty clear debug.

A single hotkey Special Key for Arrow Left/Right/Up/Down, Backspace, Esc, Tab, Enter... etc. etc... Those all work fine.  Any button with just a single key press, such as "f" which toggles a video in and out of Full Screen mode works great.  In Notepad, they all proved to execute as intended.  But again, "Space" and "Delete" do not.

If I manually press the spacebar, videos on my active screen toggle between play and pause as intended.  But the Vicreo button for these does not do anything.  And when I look at the Vicreo Listener log box, it says that "Space" was sent, but again, it does not actually execute a spacebar key press at any time.

And then, if I create a trio function that does "Command+Shift+Arrow Left" (or Arrow Right) or even "Command+Shift+left" (or right), neither of those work either.  These are supposed to snap/shift the active screen to the left/right adjacent monitor, but nothing is happening.

The Vicreo Listener log box says "key: left, type: trio, modifiers: command, shift" (or "key: Arrow Left, type: trio, modifiers: command, shift"), which seems correct, but again, it does not actually execute the screen shift to the left monitor (or right monitor when that is the key).

I don't know how many other Special Keys are not working when they are the last action of a combination or trio button, but I'm certain the arrow keys and numpad arrow keys are not working in this scenario.

Your example buttons of "ctrl+atl+tab", "alt+tab", "ctrl+v/c/x" all seem to work fine.  And since "tab" is a Special Key, it would seem that this might be exclusive to just the arrow keys, space, and delete, but I'm not sure as I didn't test every special key that exists.

I did test "ctrl+alt+Delete" trio and it did NOT work.  And it's strange that the Arrow [direction] Special Keys work when single special keys, but not when they are the last action item of combination and trio keys.

So again, "Space", "Delete", the arrow keys, and numpad arrow keys (numlock off, obviously) do not seem to be functioning properly in the latest versions.  And there could be more, I just don't know.  Most, however, do appear to be working properly.

Also, your Vicreo Hotkey help file says to "Check out the Special Keys!" and then mentions Audio volume, Play/Stop/Pause, Previous/Next track, Numpad keys, and even keyboard brightness, however I don't see any of these options in my button creation menu anywhere.  So not sure if I'm missing something or they don't actually exist yet.

I can do some screenshots if you think you need more information, but that's pretty descriptive of what's happening above.  But let me know if you need more info.

Thanks!

**Comment by JeffreyDavidsz** [comment] 2022-03-21 06:46
Hi, I've closed the previous issue, because it was related to version. It important to keep issues separated for tracking. So good you have created a new one.
Space and delete should work I'll check it next week. For the trio I the third one is programmed to be a key not a modifier, so that would explain certain keys not to work. I think it shouldn't be a problem to fix that (from my part).
I'll get back to you on this next week.

**Comment by JeffreyDavidsz** [comment] 2022-03-21 06:50
Meanwhile try "spacebar" or " " without the ". That's what my C++ code does (only on windows)

**Comment by BrianBATL** [comment] 2022-03-21 12:27
Ok I did "spacebar" as a single hotkey (NOT a Special Key) and it worked.
"Delete" in any capacity still does not work.

I look forward to hopefully seeing the Arrow keys work on trio buttons.

Thanks for the quick response as always!

**Comment by JeffreyDavidsz** [comment] 2022-03-21 13:42
Did you try "del"? I believe that should work, I'll make sure documentation will be updated soon

**Comment by BrianBATL** [comment] 2022-03-22 00:03
"del" works.

But again, only if you do a single hotkey or key press.  "Delete" and "Space" in the Special Key dropdown do NOT work.

And I tried every way I could think of to see if I could get command+shift+[direction key] to work, but nothing did.

Prior to your version that did the password, your Three Key function DID work.  It was allowing "Command+Shift+left" (or right), and was not requiring "Arrow" or considering it a Special Key.  So it appears you changed something around then.

And this is kind of a big one for me as I very often have to shift windows from a setup monitor to my monitor that's set as an input on my streaming switcher (ATEM mini pro).

I guess I could make new hotkeys with the Stream Deck program, but I already have a bunch of buttons coded in Companion using Vicreo.  And I hate how the Stream Desk software interacts with Companion.  It's not very intuitive or friendly towards each other.  I'd much rather just keep using Companion with Vicreo.

I appreciate you taking the time to work on this.

**Comment by BrianBATL** [comment] 2022-03-22 01:14
I just tested a trio of "Command+Right Shift+left" and it does some strange window rearrangement, while turning the active window into a 50% screen size.

Not that I would ever use that for anything, but I think this means that the issue on that "Command+Shift+left" snap screen left attempt is the "Shift" key second modifier.

I don't know, I'm just spit-balling and running experiments to see if I can help.  Hope this didn't confuse you.

**Comment by JeffreyDavidsz** [comment] 2022-03-27 09:52
Just noticed the Command while I was asuming your are using windows.... I need to test that on my mac

**Comment by JeffreyDavidsz** [comment] 2022-03-27 09:58
I'm confused by the different information, please provide clear questions. I'm seeing Ctrl (windows) and Command (OSX). those can be totally different issues. I'm closing this issue. Please provide per case a new issue so it's clear where the issue is comming from.
It can be totally different stuff but I need to check software in Companion, my own and different libraries

**Closed by JeffreyDavidsz** 2022-03-27 09:58 UTC
Labels: bug
